### ISSUE TITLE
Support some children for wxFrame and wxPopupTransientWindow

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#108]
### Description:

It's perfectly valid to create a control who's parent is a **wxFrame** window (or a **wxPopupTransientWindow**). Technically, the same is true of other windows such as **wxDialog** and **wxPanel**, though in those cases, a top level sizer is almost always going to work better with our UI management.

An example of this is our own **CMsgFrame** window. The entire client for this window consists of a single **wxTextCtrl**. There's no reason so use a sizer in this scenario, since the control is sized to whatever the client area of the window is. Currently, we can't implement that using **wxUiEditor** because it won't allow us to add a control without a sizer.

On the flip side, it's not that big a deal for the user to just create the child control in the derived class ctor -- we can provide the frame and optional menu, toolbar, and statusbar and leave it up to the user to create the rest. Or we could provide a limited set of controls such as a panel and/or splitter window.

**Comment by Randalphwa** [comment]
In that last large testing pass, I enabled an unlimited number of containers, splitters, and most books.

I think adding more controls to **wxPopupTransientWindow** is rather risky -- I'd worry about a dev accidentally creating a window that can't be dismissed.

Note that the MsgFrame window no longer needs a sizer since it uses a book as the top level control, and we already support that without a sizer.

I'm going to close this for now -- it can be reopened or a separate issue created if there's a specific request for a change.
