### ISSUE TITLE
For non-derived C++ generated header files, place }; after the closing comment block

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1111]
### Description:

The main reason I don't switch to a non-derived class for some of the classes in wxUiEditor is because the number of functions and methods in the header file would be impractical to add via the project file. The worst case example is mainframe.h which has a class definition of over 300 lines. That would be completely impractical to add to the project file. The other reason is that you can't do syntax checking while adding inline methods -- you have to wait until the file is generated and compiled or generated and loaded into a syntax-checking editor.

If code generation for non-derived header files placed the closing `};` after the `End of generated code` block, then a user could extend the class definition simply by inserting code before that closing `};`. The only caveat is that code generation would only write that line once -- the only time it would rewrite it would be if there was no code after the closing comment block.

```C++
// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
};  // If you need to extend the class definition, enter code before this brace
```

**Comment by Randalphwa** [comment]
The closing comment block doesn't get added until the file is actually being written. The function that writes that block doesn't even know whether we are writing a src or hdr file since the identical comment block is written to all generated C++ files.

I'm going to add a new `C++ Header Settings` category. I'll then add to this category a new boolean property that determines whether or not to generate a closing brace for the class definition. That makes it independent of being a derived class, and will not require a hack to modify the WriteFile() function.
