### ISSUE TITLE
Add preferred language keywords to var_name check

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1131]
### Description:

Since we already have strings of language keywords for C++, Python and Ruby, it would make sense to add these dynamically wherever reserved names (node.cpp) is used. The addition would be based on the current Code Preference. While it's unlikely a user would accidentally enter a reserved language keyword, it doesn't cost us anything to add that check.

**Comment by Randalphwa** [comment]
The reserved keywords are used for syntax highlighting, and only cover keywords that it is vaguelly conceivable that wxUiEditor might generate. While the C++ list is fairly complete, the other lists are not.

I think we are better off assuming the user is sufficiently knowledgeable about their preferred language that they won't use a keyword as a variable name. If they do, they'll find out as soon as the try to compile it (C++, Go, Rust) or run it (Python, Ruby, Lua). I definitely don't want to reserve all language keywords since there are keyword names in some languages that would be perfectly fine as a variable name in another language.
