### ISSUE TITLE
More suitable icons/artwork for High-DPI displays

### ISSUE THREAD

**Issue by utelle** [KeyWorksRW/wxUiEditor#1192]
I gave wxUIEditor a try recently. However, on a High-DPI display wxUIEditor is a bit difficult to use. As you can see in the screenshot below (icons marked with red ellipse) the icons in the toolbar are extremely small.

![wxuieditor-gui1](https://github.com/KeyWorksRW/wxUiEditor/assets/11139874/53997c98-2348-497a-9e73-016054e771bd)

It would be great if you could address this in a future release. Recreating the icons in different sizes is probably a lot of work. However, as an interim solution just rescaling the icons would help to make wxUIEditor more usable (even if the icons would look a bit blurry).

Besides that the icons used in the main menu have inconsistent sizes - for example, the icon for "Open Project" is larger than that for "New Project". And the icon for "Save As" is even larger. Although this is a minor issue, using the same size for all icons would make wxUIEditor look more professional.

**Comment by KeyWorksRW** [comment]
I'm going to create a separate issue for the ribbon panel toolbars and link back to this one. The underlying issue is more complicated than it would appear, primarily because `wxRibbonBar` does not support `wxBitmapBundle` like other **wxWIdgets** UI classes do. Work was started on it, but never completed, so it's not even in wxWidgets 3.3 either. I need to work on a solution that doesn't just fix the size in wxUiEditor, but also in the code it generates for other people using wxRibbonBar.

The main toolbar is created with SVG files, so technically they are the same size. However, if the SVG has a transparent border around the image then unless _every_ image has the same border around it, then scaling will make the one with the border look smaller than the one without it. I'm mixing the SVG files that are built into wxWidgets with custom SVG files that are part of the wxUiEditor repository. As you note, they don't match. I need to replace the ones added via wxART with ones that don't have the border. I'm also going to create a separate issue for this as well, because while wxUiEditor does show you what the wxWidgets art file looks like, it doesn't show a border so it's impossible to tell how it will scale.

**Comment by utelle** [comment]
> I'm going to create a separate issue for the ribbon panel toolbars and link back to this one. The underlying issue is more complicated than it would appear, primarily because `wxRibbonBar` does not support `wxBitmapBundle` like other **wxWIdgets** UI classes do. Work was started on it, but never completed, so it's not even in wxWidgets 3.3 either.

That is a pity.

> I need to work on a solution that doesn't just fix the size in wxUiEditor, but also in the code it generates for other people using wxRibbonBar.

As I see it you use a function `wxueImage()` to convert the raw PNG data into a `wxImage`. This function could be changed to rescale the image based on the current screen resolution before returning the image object:

```C++
    image.Rescale(w->FromDIP(image.GetWidth()), w->FromDIP(image.GetHeight()));
```

where `w` is a pointer to the `wxWindow` object to which the image is added - `w` has to be added to the parameter list of the function.

> The main toolbar is created with SVG files, so technically they are the same size. However, if the SVG has a transparent border around the image then unless _every_ image has the same border around it, then scaling will make the one with the border look smaller than the one without it.

Thanks for the explanation. I was not aware of those transparent borders.

> I'm mixing the SVG files that are built into wxWidgets with custom SVG files that are part of the wxUiEditor repository. As you note, they don't match. I need to replace the ones added via wxART with ones that don't have the border.

AFAICS the SVG icons used by wxART are coming mostly from the [Tango icon theme archive](http://tango.freedesktop.org/releases/tango-icon-theme-0.8.90.tar.gz). Since the SVG files were converted to **.h** files for wxART it is hardly possible to adjust them within wxART, but the [Tango icon theme archive](http://tango.freedesktop.org/releases/tango-icon-theme-0.8.90.tar.gz) contains the original SVG files, which could be adjusted for wxUiEditor.

**Comment by KeyWorksRW** [comment]
For wxUiEditor, it would depend heavily on how well those images scale via wxWidgets. My experience has been that some images scale up with high quality set, some need lower quality set because high-quality scaling messes up the image, and in some cases none of the scaling options work and it needs some hand-tweaking and a separate image. On top of that, some of the bitmaps are very amenable to converting to SVG because they should then scale correctly for any size. That means that sometimes there will be a single PNG file, sometimes two PNG files, and sometimes a SVG file -- which means I need to get that into a BitmapBundle and let the bundle handle any further scaling. For two PNG files, BitmapBundle will either use the bitmap that is already scaled for the current DPI, or it will start from the bitmap that is closest to the size it needs to scale to.

I've got a copy of the Tango set, but I see now that InkScape has changed the default DPI so I'm definitely going to need to rework both the SVG files I'm already using, as well as replacing _all_ of the wxART files to make certain all the SVG files are using the same default DPI.

**Comment by utelle** [comment]
> For wxUiEditor, it would depend heavily on how well those images scale via wxWidgets. My experience has been that some images scale up with high quality set, some need lower quality set because high-quality scaling messes up the image, and in some cases none of the scaling options work and it needs some hand-tweaking and a separate image.

Yes, of course. However, most PNG files you are using for the ribbon bar have a resolution of 22x22 pixels. I doubt that anything serious goes wrong on upscaling by a factor of 2 (or 1.5).

> On top of that, some of the bitmaps are very amenable to converting to SVG because they should then scale correctly for any size.

Using SVGs wherever possible is certainly the best option, but converting to SVG may take quite some effort.

> That means that sometimes there will be a single PNG file, sometimes two PNG files, and sometimes a SVG file -- which means I need to get that into a BitmapBundle and let the bundle handle any further scaling.

Using bitmap bundles for better support of high DPI screens is certainly the way to go. However, as an interim solution it might be an acceptable compromise to just rescale the small PNG images automatically. IMHO that is better than having those extremely small icons, even if the quality is low.

> I've got a copy of the Tango set, but I see now that InkScape has changed the default DPI so I'm definitely going to need to rework both the SVG files I'm already using, as well as replacing _all_ of the wxART files to make certain all the SVG files are using the same default DPI.

In the SVG files themselves I don't see any DPI values. So, I'm sure what has to be done to adjust the SVG files.

**Comment by KeyWorksRW** [comment]
High DPI ribbon bar and navigation panel is in, so I'm removing the milestone, but leaving the issue open because I still want to work on better high resolution display images.
