### ISSUE TITLE
Bug: wxScrolled<wxPanel> doesn't allow children

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1205]
### Description:

wxScrolled<wxPanel> needs to support the same children that wxPanel supports.

**Comment by Randalphwa** [comment]
The type is `container` so it takes all the children a container takes, which is primarily sizers. I added a commit that automatically adds a box sizer when a wxScrolledWIndow is created, just like it does when a wxPanel is created. That should avoid some of the confusion. Importing is going to be an issue, since a user doesn't have to use a sizer. We don't support that, so this might require forcing a sizer with no borders.
