### ISSUE TITLE
Bug: "static const int form_id" results in an "undeclared" identifier

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1282]
### Description:

the highlighted row does not permit file compilation
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/e28005eb-2438-440c-85d0-b7b90d94021d)

it results in an "undeclared" identifier
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/f35aa259-e6e3-48d6-a67e-5a7ce303b095)

I think constants declaration should be moved just before `protected:` section 
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/adb58ded-3ff2-4849-a393-2727c1bcd18f)

**Please take in consideration** that the form_style constant has not the   same value as form constructor style.

**Comment by Randalphwa** [comment]
If you move it below Create, then you cannot use the values for construction or the `Create()` function.. I.e., you could _not_ enter:

```c++
CMainFrameDesigner(wxWindow* parent, wxWindowID id = formid, const wxString& title = form_title(), ...)
```

I agree that it should be generated _after_ the enumerated ids, but I think it should remain above the ctor methods so that the constants can be used in the ctor/Create() methods.

**Comment by rossanoparis** [comment]
OK but ... CMainFrameDesigner is a class defined in a wxUiEditor file, I can not modify it.
Since you don't use constants in constructur and create functions, you shouldn't need to define constatns above that functions.
If you are planning to use constants in your generated code then, yes, it is nessary to define constants above.

In all other cases, since I need to include wxUiEditor files I can use `CMainFrameDesigner::form_id` and so on ...
Even for derived classes.

anyway, actually it is necessary to avoid to generate `static const int form_id` before enums, because now is a blocking bug, the user is not able to compile its source code.

I think you could let all as is, cimply not creating `form_id` constant as, if I'm not wrong, a user could use `CMainFrameDesigner::ID_CMAINFRAME` instead.
Yes, perhaps this is the best solution

**Comment by Randalphwa** [comment]
On Wednesday, November 8th, 2023 at 12:05 PM, Rossano Paris ***@***.***> wrote:

> OK but ... CMainFrameDesigner is a class defined in a wxUiEditor file, I can not modify it.

There a couple of ways to modify the class file. You can go to the C++ Header Settings and check "no_closing_brace" at which point you can add anything you want to the class declaration after the closing comment block. Of course that's not going to help in situations where the position of the member declarations are critical for the compiler.

The other way to modify the header file is the "inserted_header_code" also in the C++ Header Settings. However, that still doesn't resolve your issue since it's inserted at the end of the public section, so after the Create function is declared. If the position of the added header declarations isn't important, just shut off the closing brace and add your additional class methods/members/definitions after the final comment block.

Just as an aside, I rarely use derived classes in wxUiEditor any more. Once I added properties letting you add methods and members to the header file, as well as the ability to edit generated source file (after the final comment block), I implement event handlers and custom methods in the generated file instead of using a derived file. For me, I prefer having all the code in a single source and header file, instead of two additional files beyond what gets generated. The only time I don't is the edited class contains a lot of additional code, members, and methods. If it's too much code, then I'll derive from the class instead of editing it directly.

> Since you don't use constants in constructur and create functions, you shouldn't need to define constatns above that functions.
> If you are planning to use constants in your generated code then, yes, it is nessary to define constants above.
>
> In all other cases, since I need to include wxUiEditor files I can use CMainFrameDesigner::form_id and so on ...
> Even for derived classes.
>
> anyway, actually it is necessary to avoid to generate static const int form_id before enums, because now is a blocking bug, the user is not able to compile its source code.

Agreed, and I will change the order of the enums, placing them before any static const declarations.

> I think you could let all as is, cimply not creating form_id constant as, if I'm not wrong, a user could use CMainFrameDesigner::ID_CMAINFRAME instead.
>
> Yes, perhaps this is the best solution

I don't think adding the enums first after the public: section is going to be a problem. It can push the construction and Create declarations down a ways, but I don't think those are terribly important in terms of code readability. The customization of the class is primarily the enums/constants, and the event handlers and class member functions, which are easily located in the generated header file.

**Comment by rossanoparis** [comment]
> There a couple of ways to modify the class file. You can go to the C++ Header Settings ...
> The other way to modify the header file is the "inserted_header_code" also in the C++ Header Settings. ...

Thanks for the tips

> Just as an aside, I rarely use derived classes in wxUiEditor any more. Once I added properties letting you add methods and members to the header file, as well as the ability ...

I see, but I prefer maintain the files generated by the RAD tool as they are, without adding anything not related to widgets creation. Other stuff related with the application itself are handled by the final object, which inherits the class generated by wxUiEditor.
This is the way I use, it is a different approach, but I think the final project is more tidy and clear to understand.

Anyway, please feel free to solve this issue using the best way for you.
I think that moving IDs declarations in the position you mentioned is a goos idea.
