### ISSUE TITLE
Dialog units and platforms

### ISSUE THREAD

**Issue by gmayo1947** [KeyWorksRW/wxUiEditor#1295]
I have only just recently discovered your program and am still in the throws of trying it out. I suspect I still have a bit to learn. However, there are two things that struck me. First is the use of dialog units. This can be turned off but has to be done on a control by control basis as well as a property by property basis. To me, it would make life easier if this was a selectable project option as happens with wxGlade. Then this only needs to be done once.

The other thing is that virtually all controls have a platforms property. Again, rather set or turn off options on a control by control basis, it would be nice if there was just a single option to make this choice.

I like what I see so far and will continue to watch the progress of this application.

**Comment by Randalphwa** [comment]
That's a good idea about providing a project-wide option to provide a project-wide option to turn off the default dialog units. What is _not_ practical to do is to change any dimensions that already do or don't use dialog units. So if a user turns off dialog units, creates their project, and then discovers that the program looks terrible on a high-resolution display, they will have to manually turn on dialog units for every dialog/control where a non-default dimension was used. That's why the default is to use dialog units -- user's may not realize how important that is as more and more people are using 4k and higher displays. Of course ideally, you don't use dimensions any way unless you absolutely have to, since wxWidgets _will_ create controls that take into account scaling for high-resolution displays.

I'm not sure what you are envisioning for platform specific code. If you set the default platform to UNIX for example, then every control would only be created if the program was compiled on UNIX. You have then effectively made a program that will not run on Mac or Windows. What would be the advantage of making it the default to prevent your program from compiling/running on other platforms?

Currently, the point of the platforms settings is when some specific control isn't going to work correctly on a specific platform. For example, you can create a text control that has spell checking that works on Windows, but you might want to create a custom control where you provide your own spell-checking that works on Unix (Unix doesn't support native spell checking for a text control).

**Comment by gmayo1947** [comment]
Yes, I have totally missed the point of platform settings. When I saw that property, i said "I only want a windows app and don't other platforms". I later realised I was on the wrong wavelength when I found my test Python app wouldn't run because of all the "if (define windows)" scattered through it. Then I belatedly found I would have seen that if I had looked at the source code - that's a nice feature by the way.

Thanks for explaining the use of dialog units. I haven't worked with dialog units since the early 2000's when they were part of Powerbasic. I'll try using the default for a bit and see how it goes.
