### ISSUE TITLE
Change Open Recent menu to a launch of the Start dialog

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1331]
### Description:

The problem with Open Recent menus is that they typically show the entire path, and you have to look at the end of that path to see if it's the file you want. With wxUiEditor, we have a Start dialog that shows just the file name first, followed by the path. Often that short name is all you need to know -- the only the time the path will matter is when you have two projects with the same name in different directories.

Changing the Open Recent menu to "Open Recent..." and using it to launch the start menu would make it easier to get to recent projects. While it is a non-standard approach to how recent files are normally access, I think the clarity of the Start dialog along with the additional ability to change your mind and choose New or Import outweighs the non-standard approach.

**Comment by Randalphwa** [comment]
PR #1334 essentially did this. I added a Different Project command at the top of the File menu that launches that Startup Dialog, and replaced the New and Open toolbar tools with a Different Project tool that does the same thing.

On the File menu, I left the New, Open and Recent Files just for those folks that are used to them and might otherwise be confused by the lack of them.
