### ISSUE TITLE
Bug: C++ base_directory in Project settings is not works well

### ISSUE THREAD

**Issue by Kumazuma** [KeyWorksRW/wxUiEditor#1366]
### Description:

When I set base_directory to "generated" and generate code, files are not created.
The project file is located at src/ui
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/12020335/1149af7f-f5ba-4e55-91a4-02f980c6c295)

**Comment by KeyWorksRW** [comment]
Would I be correct in assuming that you only have a single "generated/" directory under src/ui/? Also, is there also a "generated/" prefix in the publicationframe that you specified as the base_file for the frame you are creating?

**Comment by Randalphwa** [comment]
This has been fixed via PR #1371 and should appear in Daily Builds starting on 1/8.

The issue was that the Project file specified generated as the base_directory, and the form's base_file also specified the same folder. A check is now made for that situation, and it will now work correctly with or without the folder name in the form's output file starting with the same folder name as the Project's base_directory.

Thanks for reporting this!
