### ISSUE TITLE
Bug: wxAuiNoteBook's stype property editor is a combox(wxChoice), not the checked listbox

### ISSUE THREAD

**Issue by Kumazuma** [KeyWorksRW/wxUiEditor#1416]
### Description:

wxAuiNoteBook's stype property editor is a combox(wxChoice), not the checked listbox. so I can not choice multiple styles.
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/12020335/c2619f75-191e-40e9-a373-002959419c1c)

**Comment by KeyWorksRW** [comment]
This was fixed in commit: #1353 -- the commit doesn't specifically refer to this issue but that was when it was changed. When the options were moved back into the XML interface, the `style` property type was changed from `option` to `bitlist` which displays as a checked list. This is part of the current daily builds, and will be part of the 1.2.1 release.
