### ISSUE TITLE
Bug: stdButton ButtonClicked-Event giving an error (and close doesn't close)

### ISSUE THREAD

**Issue by PasstScho** [KeyWorksRW/wxUiEditor#1527]
Using:
wxUiEditor 1.2.9 on Debian12
Python 3.11.2
wxPython Version: 4.2.2

### Description:

When using stdBtn on a wxDialog, I want to use "Close" and "Ok" buttons. Ok works, but "Close" doesn't work. When I add a custom Event method under Events -> CloseButtonClicked e.g. "on_close_btn" it will generate wrong code.

Steps to reproduce:
- Create a new project
- add a wxFrame with Standard Buttons
- Click on "stdBtn" Properties, uncheck "Cancel" and check "Close"
- go to Events and add "on_close_btn" to CloseButtonClicked
- Click on Python-Tab to check code
- see self.Bind(wx.EVT_BUTTON, self.on_close_btn, wx.ID_CLOSE)
will generate a runtime error:
  File "/dlgbase.py", line 82, in __init__
    self.stdBtn_Close.Bind(wx.EVT_BUTTON, self.on_close_btn, wx.ID_CLOSE)
  File ".../myenv/lib/python3.11/site-packages/wx/core.py", line 1480, in _EvtHandler_Bind
    assert source is None or hasattr(source, 'GetId')
           ^^^^^^^^^^^^^^

### Quickfix:
instead of using parameter "wx.ID_CLOSE" it should use the button "self.stdBtn_Close" so the line will be:
self.Bind(wx.EVT_BUTTON, self.on_close_btn, self.stdBtn_Close)

I'm not an export on wx or python but this is how it works for me. 
Of course it would also be great if a "close" button already closes the Dialog without additional steps. It is already registered as Cancel button by "self.stdBtn.SetCancelButton(self.stdBtn_Close)" but this could also be a wx issue...

**Comment by Randalphwa** [comment]
# Python

If the window isn't known, then the correct form of the bind call would be:

```python
self.Bind(wx.EVT_BUTTON, self.on_close_button, id=wx.ID_CLOSE)
```
that infers a `source=None`

In this case, since the button window is known, it should indeed be used instead of the id, which allows the id to be used elsewhere with a different event handler.

# Ruby

We already create a local `_ok_btn` so it would make sense to create a local button for any other button that needs an event handler. That would allow us to call `evt_button` directly instead of `Bind()`.

It might also make sense to use the same naming convention used for Python: `_std_btn_close` instead of `_close_btn`

**Comment by Randalphwa** [comment]
I checked, and no, `self.stdBtn.SetCancelButton(self.stdBtn_Close)` does not automatically call the wxWidgets code to close the dialog in Python. I also tried removing that call entirely, since if the button is not set in C++ then the default functionality _is_ called, but wxPython insists I set the CancelButton or it won't show up at all.

In the incoming PR that fixes this, if you haven't added the event handler yet, it will show up in the commented event handlers with the necessary call to close the dialog. That makes copying/pasting the event a bit easier...
