### ISSUE TITLE
Bug: Inserting a wxScrolledWindow using wxScrolled<wxPanel> results in a compilation error

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1551]
### Description:

wxWidgets version: v3.0.0 master (09 September 2024)
exUI: latest "Daily build"
Compiler: VS 2022 v17.11

The code below which is generated by wxUI generates the following error
`Error C2440	'=': cannot convert from 'wxScrolled<wxPanel> *' to 'wxScrolledWindow *'`

**wrong code**
```
m_scroll_panel = new wxScrolled<wxPanel>(m_panel7, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL);
```

In order to make the code above working, it is necessary to declare `m_scroll_panel` in this way `wxScrolled<wxPanel>* m_scroll_panel;` without using `wxScrolledWindow*`

Declarations using wxScrolledWindow* require the code below ...

**correct code 1**
```
m_scroll_panel = static_cast<wxScrolledWindow*>(new wxScrolled<wxPanel>(m_panel7, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL));
```

**correct code 2**
```
m_scroll_panel = new wxScrolledWindow(m_panel7, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL);
```

**Comment by Randalphwa** [comment]
It's a mismatch between the generated source and header files. The header file is declaring this as:

```C++
wxScrolledWindow* m_scroll_panel;
```
 whereas the source file is declaring this as:

```C++
m_scroll_panel = new wxScrolled<wxPanel>(...);
```

If `wxScrolledWindow` was a true template it wouldn't matter. However, `wxScrolledWindow` is a class derived from `wxScrolled<wxPanel>`. The `wxScrolledWindow` class doesn't add anything to the `wxScrolled<wxPanel>` class, but it cannot be used interchangeably.

Unfortunately, `wxScrolledCanvas` is an actual typedef (`wxScrolled<wxWindow>`) and can be used interchangeably. Which means that the one called a Window is a panel, and the one called a Canvas is a Window. Guarenteed to confuse someone new to wxWidgets... 😢 

Note that the current wxWidgets documentation is wrong, since it incorrectly claims that wxScrolledWindow is a typedef, when in fact it is declared as:

```C++
class WXDLLIMPEXP_CORE wxScrolledWindow : public wxScrolled<wxPanel>
```

Most existing code, including all but one of the wxWidgets samples use `wxScrolledWindow`. That means AI is going to suggest using `wxScrolledWindow` for those coding manually with AI assistance. Both Ruby and Python went with `Wx::ScrolledWindow` and `wx.ScrolledWindow` respectively. I think it makes sense to drop the use of `wxScrolled<wxPanel>` and generate `wxScrolledWindow` instead.
