### ISSUE TITLE
Add limited support for wxTimer

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#343]
### Description:

There are roughly 9,000 formbuilder projects on GitHub, and only 48 of them use a **wxTimer**. That would indicate that it's not commonly used. Nevertheless, those 48 projects will not work the same if they are imported into **wxUiEditor**.

One option would be to add the class, but not add a toolbar button for it. That allows import to work, and users who search for it can find and insert it, but it doesn't clutter up the toolbar with something so rarely used. This would be similar to how we will probably need to fix issue #230.

**Comment by Randalphwa** [comment]
**wxFormBuilder** has `enabled` and `one-shot` properties either of which will start the timer in the form's constructor. In the case of a dialog, that means the timer starts before the dialog is shown.

I'm at a loss as to why this would be useful in the base class. It seems far more appropriate, particularly for dialogs, for a timer to be started in the derived class's wxEVT_INIT_DIALOG handler. If the caller starts it in their derived class then it's a simple matter to add the member to their derived class header file rather than in the base class.

I'm closing this unless someone can give me a valid scenario as to why it would be useful in the base class.
