### ISSUE TITLE
Add Import Project... menu command, modify Append menu command

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#344]
### Description:

It's not obvious from the menu name that `Open Project...` can be used to import any type of project. It's also not obvious that you can import multiple projects into a single **wxUiEditor** project by first creating an Empty project.

Adding a `Import Project...` menu command above the `Append` menu should make it clearer. It should get it's own dialog that includes the output project name while using the multiple import projects that the Empty Project dialog uses.

Along those lines, the `Append` menu could also be changed to `Append Project...` and would use a dialog similar to the above-mentioned import dialog. The only difference is that the output filename is already known, so no need to show it.

**Comment by Randalphwa** [comment]
Putting the `Import...` command as the last line of the Open commands makes it more obvious that this command will create a new project.

I'm dubious about the value of changing Append. If the user does need to append several projects, then the change would be convenient, but if the user only wants to add one, it makes it a bit more awkward. Where things would get really dicey is if we add the ability to append **wxUiEditor** projects. Since those projects can have multiple forms, wanting to append multiple projects is both unlikely and could result in a very unwieldy project.
