### ISSUE TITLE
Add support for namespace on a per-form basis.

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#568]
### Description:

While it would make sense to add the project's `name_space` value as an auto-complete, each individual form should be able to have it's own unique namespace value.

**Comment by Randalphwa** [comment]
Note that this complicates code that checks for duplicate class names. Currently, you can't have a class with the same name elsewhere in the project, since normally that would generate a linker error for C++. For Ruby and Python, this would be fine as long as the output file was unique -- it would be up to the dev to decide which module to load in their application.

Where things become really problematic is if a namespace for a form was used to create a unique name even though the root name was identical with another form. We could get this to work, by removing the duplicate check if name_space was added. However, if the user removed that namespace, the dev will now have a project that cannot be linked because of duplicate class names.

While just adding a form name_space would be quite easy to do, I think we would still need to insist on unique names for form classes.
