### ISSUE TITLE
Bug: The editor is not DPI-aware

### ISSUE THREAD

**Issue by PBfordev** [KeyWorksRW/wxUiEditor#590]
If one runs the editor on MSW with a display using non-default DPI, the GUI is noticeably blurry. This is because the application is not marked DPI-aware and the OS has to rescale it as bitmap.

The issue could be simply fixed by marking the application as DPI-aware in its application manifest, wxWidget 3.1.5 has support for high DPI displays on Windows as long as the application is marked as PerMonitor v2 aware. However, this would assume the code itself is DPI-aware, which is probably not true.

**Comment by KeyWorksRW** [comment]
The manifest file already has:

```
<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, system</dpiAwareness>
```

That should result in borders in the UI automatically increasing, but that won't help the art problem since those images still have to be scaled. Ultimately, a second set of artwork needs to be created with code that switches to it when a higher resolution is available. That also needs to get tied into the code generation since the issue affects anyone creating a dpi-aware app.

I'm adding the enhancement label for the additional artwork, but I still want to take a pass through all of the UI to verify the borders are all correctly changing.

**Comment by PBfordev** [comment]
At the first glance, the DPI-awareness part in the manifest embedded in `wxUiEditor.exe` looks correct or at least same as the one [wxWidgets has](https://github.com/wxWidgets/wxWidgets/blob/1be048fc53df01ebf2c39920a43f97c64427417d/include/wx/msw/wx_dpi_aware_pmv2.manifest#L15) and which works. 

However, the executable is for some reason still not DPI-aware. It is obvious at the first glance if one runs on HiDPI system: It is blurry. If one does not have a high DPI system, it can be checked with Task Explorer, in the Details page, by adding column "DPI Awareness" and checking its value there.
