### ISSUE TITLE
Problems with opening a recent project

### ISSUE THREAD

**Issue by PBfordev** [KeyWorksRW/wxUiEditor#602]
Opening a recent project either from start screen or menu File / Open Recent may not work.

For some reason, the projects (even the same one, twice) can be displayed with or without a file extension (.wxui). Opening works only for the projects with an extension displayed. In the Open Recent menu the same project can be displayed twice, once as a filename with an extension and once as a path without an extension, only the former can be opened.

For example, the first two projects refer to the same project but only the first one can be opened. 
![image](https://user-images.githubusercontent.com/12495521/148677522-77c6eb78-5a28-4042-9e92-15f470d1270a.png)

Also, in the start screen above, there is no option to start with an empty project.
BTW 2, it would be better if the folder names were ellipsized in the middle instead of being cut-off towards the end.

**Comment by KeyWorksRW** [comment]
See issue #608 -- most of the problems reported here are due to incorrect resizing.

The non-sizing issue here is that a new project that has not been saved is getting added to the LRU history. Not only is that creating mess for the history, but it's also potentially flushing out valid projects. Marked as high priority, because people trying out the editor are likely to create a lot of empty projects while they try things outs.
