### ISSUE TITLE
Use better default names for classes and files

### ISSUE THREAD

**Issue by PBfordev** [KeyWorksRW/wxUiEditor#605]
Currently, the default file names for generated base code are always the same generic "filename_base". I believe it would be better if the file name was derived from the class name, e.g., "MyFrame_base" for class "MyFrameBase".

The name of the derived class is always "Derived class". I believe it would be better if the name was derived from the base class name, e.g., "MyFrame_derived" for class "MyFrameDerived". Perhaps the derived file name should also be prefilled, just like the base file name is?

**Comment by KeyWorksRW** [comment]
I wondered if the use of `filename_base` as a flag that the user didn't specify anything was going to be confusing -- this issue confirms that indeed it is confusing.

The properties `base_file`, `derived_class_name`, and `derived_file` all change when the user changes the base `class_name` property. Prefilling them with placehoder names is what's causing the confusion. We do need to use something in the `Source` code display for the `#include` line, which is why `filename_base` was used, but we should be able to special-case an empty field for this property and hard-code a temporary name.

It makes sense to have these fields be empty to avoid confusion -- we should add a tooltip to indicate that the class name should be changed first.

While we're making changes to avoid confusion, the Derived panel should display something to indicate why it's blank (the user didn't specify a class name for it).

**Comment by PBfordev** [comment]
> It makes sense to have these fields be empty to avoid confusion

I guess it is a matter of opinion. I prefer to have those prefilled with sensible defaults. IMO, when a class is renamed, the user should be notified about this and asked whether the file names should be changed as well.

**Comment by KeyWorksRW** [comment]
PR #636 also improves automatic file naming, though the addition of the option to create a non-derived class means that the derived class name and file will be ignored if the user prefers to create a non-derived class. We still don't auto-create a base filename if the default class name is used. The assumption here is that by the time the user actually wants to generate the code rather than just looking at what would be generated, they will also switch to a more reasonable class name which will automatically fill in a suggested file name.
