### ISSUE TITLE
Replace the opening Splash window with a dialog that properly resizes

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#608]
### Description:

Issue #602 is a good example of what happens when the Splash dialog doesn't get resized correctly. In the screenshot, the "Create an empty project" is missing entirely, and the paths are truncated.

The root of the problem is that the html window we're using doesn't generate a best-fit size, so we're trying to hard-code the largest possible size, and that's clearly not working.

This window needs a completely new design that doesn't use and HTML window so that it will properly resize.

**Comment by PBfordev** [comment]
I, for one, would prefer the design similar to (simplified) MSVS start screen. 

In other words, on the left side having "Open recent" with a scrollable list of recently used projects. 

On the right side, having buttons for "Open existing", "Create empty", "Import...". The window should be scrollable when needed.

TBH, I would prefer having the usual program setting where I can choose what happens when the program starts, usually there is something like "Show start screen", "Open latest project" and "Create empty project". But of course, I do understand that this is not something you should spend your time and effort on.

**Comment by KeyWorksRW** [comment]
Definitely a good time to simplify that dialog box. It was created back when Importing just popped up a file open dialog box, so I wanted some way to indicate what could be imported. The new Import dialog makes that obvious, so there's no longer a need for the explanation of what can be imported.

I've added a note to my internal todo list to add a setting controlling startup behaviour, but it will be quite awhile before I get to that -- still way too many things I want to add/improve with this editor. For Windows users, opening a specific project is as simple as dragging the project file to the desktop and creating a shortcut. Supposedly, the setup program for Unicode will enable that as well, though the Unicode build is also a ways off. That said, a lot of users are only going to be working on a single project, and automatically opening the last project would be useful.
