### ISSUE TITLE
Bug: Assertion error showing hidden files in wxGenericDirCtrl

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#642]
### Description:

Under a Debug build of **wxUiEditor**, calling `wxGenericDirCtrl::ShowHidden(true)` causes an assertion error in the Mockup panel using 3.1.15 of wxWidgets. The problem is that a treectrl item in the generic directory doesn't exist. First off, we need to find out if the code generated causes the same problem. Note that both wxFormBuilder and wxCrafter generate the same code we do, but that doesn't mean that debug programs built off that code don't generate the same assertion error that the debug build of wxUiEditor gets. In any event, this needs to get checked out.

**Comment by Randalphwa** [comment]
I'm not sure what changed, but I'm no longer seeing this problem using 3.2.0 instead of 3.1.5. I don't know if that's because something changed in the wxWidgets code, or if there's some specific directory where this occurs, but without any further repro information, there's nothing that can be done here.
