### ISSUE TITLE
Custom control parameterization and its representation

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#824]
### Discussed in https://github.com/KeyWorksRW/wxUiEditor/discussions/821

<div type='discussions-op-text'>

<sup>Originally posted by **hobbitdev** November 12, 2022</sup>
**custom control parameters**
Here below a sketch of what I'm going to propose regarding custom controls parameterization.
Following the way used by wxDialogBlocks, it would be very helpful to improve the control parametrisation usign the way shown below.
With five optional parameters, you can obtain a better code for instancing new custom controls ...

remark: I used a wxSplitterWindow as parent only to make a quick sketch; I know it doesn't make sense to express size for the custom control, in this case

**custom control representation**
Another useful feature is related to "Mock up" context. It would be nice to draw the area occupied by custom control respecting the size inserted using properties tab.
Otherwise the entire layout drawn in "Mock up" context doesn't respect the final layout.

![image](https://user-images.githubusercontent.com/33904565/201479555-8fd56849-a7e7-4bae-a637-b20cf31c97a5.png)

Best regards
Rossano</div>

**Comment by hobbitdev** [comment]
Thank you @KeyWorksRW for accepting this proposed enhancement. 

If I can, I'd like to add another parameter which I forgot to describe in my previous discussion.
The parameter should be {NAME} useful to parametrize the "window_name" property.

This last one, compleates a good parameterization for custom controls derived from wxControl class, which should be the common case.

Regards
Rossano

**Comment by KeyWorksRW** [comment]
Note the link to #360 -- implementation should have a custom dialog so that macros can be easily added to the string. Also adding this to the 1.1 milestone -- all the planned custom control enhancements should be added to this release since they will require adding new properties.

**Comment by hobbitdev** [comment]
It seems OK, even though I wouldn't get rid of the opportunity to add free text, as often it is needed

**Comment by Randalphwa** [comment]
I'm inclined to use the actual property names rather than shortcuts like ${NAME}. My reasoning is that someone reading that string might wonder whether ${NAME} refers to the variable name, the class name, or the window name. Using ${window_name} eliminates any possibility of confusion.

${STYLE} also won't work once I add the ability to inherit from a specific wxWidgets class -- in that case, you wouldn't know whether style referred to the inherited class `style` property or the `window_style` property. As with name, using ${window_style} avoids any possible confusion.

Note that implementation for the string will support either all lower-case names or all upper-case, but not mixed case names. For the custom parameter editor, only lower case will be offered for those using the drop down and button to add the macro, though of course the user can edit it after it gets added.

**Comment by hobbitdev** [comment]
it sounds good, thank you for sharing

**Comment by KeyWorksRW** [comment]
It's worth calling attention to PR #1300 which adds a new `construction` parameter to custom controls that allows a dev to completely bypass the construction created by wxUiEditor. This is the approach used by wxFormBuilder and wxGlade, so the PR also updates the importers to support that method. What this ultimately does is give you a choice -- you can specify the parameters and let wxUiEditor figure out the construction based on those, or you can simply create the entire construction code yourself.

**Comment by KeyWorksRW** [comment]
Assuming I don't accidentally break the build today 😁, then yes it should
show up tomorrow (11/24) -- build #154

**Comment by rossanoparis** [comment]
I had a look at the latest build, and I found it useful. Your attention to make importing projects easy and reliable is very remarkable. 
I successfully imported 45 projects from FB using the v1.1.2

Regarding custom controls it seams that the only thing remain to implement is a rectangle rapresentation which respects the given size.
I'm planning to import uge projects made using DialogBLocks, but it is not possible up to now due to this missing feature.
I can't wait to see it implemented :)

**Comment by KeyWorksRW** [comment]
As much as I can, I want to provide a smooth upgrade from any of the major
designers (wxDialogBlocks, wxCrafter, wxFormBuilder, wxGlade, wxSmith).
Currently, I'm working through the kicad repository which has 151
wxFormBuilder projects -- and there's some things that aren't converting
correctly. After that, I want to work more on custom controls. That should
be the last piece to add before releasing 1.2. After this release, I'm
planning on maintaining a hotfix branch so that I can quickly fix any bugs
that are found without holding up the main development branch. That way if
you or anyone else does encounter any problems either from importing, or
from code generation, I can get out a fix more quickly then the last two
6-month release cycles.

**Comment by KeyWorksRW** [comment]
I ran out of time before I could fully test this, though from what testing
I did do, PR #1311 does what you need and a bit more besides. By default,
Custom Controls will look at the new custom_mockup property to get the size
to display. If those values are both -1, then it will look at the size
property in the Windows section (which is where DialogBlocks imports get
placed) and use that if either width or height is -1. The custom_mockup
allows you to override the size to display the control in the Mockup panel
without affecting code generation.

The dialog for editing custom_mockup has a drop-down that currently is
ignored, but will ultimately provide some choices as to what wxWidgets
control to use to represent the Custom Control in the Mockup Panel.

This should be in daily build 157

**Comment by rossanoparis** [comment]
Thank you @KeyWorksRW indeed an useful implementation ...
Regarding the way the control is drawn, I think a simple rectangle would be an enougth option, as what is useful is to draw the boundary of control area.

Anyway, thank you

**Comment by KeyWorksRW** [comment]
One of the options I want to add to that drop down is wxStaticText which
would be drawn with a simple border. If no text is supplied, you would
simply get a rectangle with a border, with text would display the text
horizontally centered within the border.

**Comment by rossanoparis** [comment]
.... that's a good idea
