### ISSUE TITLE
wxLua problems

### ISSUE THREAD

**Issue by Randalphwa** [KeyWorksRW/wxUiEditor#842]
### Description:

I'm adding this issue now because it needs to be resolved before the 1.1 release -- as the situation currently stands, wxLua code generation should be dropped before the release. I want to leave this issue open in case an official binary of wxLua 3.2 becomes available and/or I am able to get a build of wxLua working well enough to incorporate into wxUiEditor.

wxLua doesn't have any current official binaries for Windows available -- the closest is ZeroBrane Studio, but that uses wxWidgets 3.1.4 and an even older version of wxLua (3.0) which presumably means wxWidgets 3.0. Even with the non-official binary built on 3.1.5 that I was able to find, my code generated dialog works with wxLua.exe but not with ZeroBrane. It works with Lua 5.4, but not LuaJIT. I have been unable to get wxLua to build, so currently I have no way to test the output if I generate code that utilizes wxWidgets 3.2 functionality.

The other issue with wxLua is events -- with C++ and wxPython, I can generate a placeholder function and bind to it. The wxLua `Connect` function is designed to have the full definition of the function as part of the call. That's essentially equivalent to using C++ Lambdas for the event hanlding, but I don't currently have a good way to generate or store a Lua equivalent.

wxLua works well with XRC files. These have the advantage that for the most part they simply ignore any properties that are newer then the specific version of wxWidgets being used. We already generate XRC files, so it might make more sense to not expose wxLua code generation at this time. I'd probably keep working on generating the code, but move it into the internal builds for now. I do have a side project of trying to get wxLua to build with LuaJIT and then incorporate that directly into wxUiEditor. Should that actually get implemented, then it would be a lot easier to generate wxLua code and potentially include it inside of a Lua code editor that would be part of wxUiEditor.

**Comment by KeyWorksRW** [comment]
ZeroBraneStudio has stated they have no current plans for creating a release with wxLua 3.2. While the wx shared library is built with wxWidgets 3.1.4, the wxLua version is 3.0.0, so presumably none of the newer control properties would be available. It also means no support for hi-DPI displays, no SVG files, none of the XRC enhancements added to 3.1.7, etc. There's still a possibility I can integrate wxLua into wxUiEditor which would at least provide a Windows version of wxLua that people could use. However, I'm going to assume that just prior to the beta, all wxLua-generating functionality will need to be allowed in internal builds only.  Since it looks like the only way for people to get a wxLua 3.2 binary is if we provide it, we should either generate code assuming 3.2 or none at all. That matches the wxPython code which _is_ available as a 3.2 binary.
