### ISSUE TITLE
Bug: Series of errors importing wxFormBuilder project

### ISSUE THREAD

**Issue by hobbitdev** [KeyWorksRW/wxUiEditor#852]
### Description:
I'm facing problems importing wxFormBuilder projects
Below an image with their description.

The only way to fix the reported issue marked with (*1) is to delete and recreate it, with its related event function; which could be a problem importing project with several toolbar and tools on them.

Other issues, still remain even recreating objects

zip file with projects ...
[wxfb.zip](https://github.com/KeyWorksRW/wxUiEditor/files/10135922/wxfb.zip)

![image](https://user-images.githubusercontent.com/33904565/205146493-e8b04f65-3c00-44ee-a37f-7cf7208dda94.png)

**Comment by KeyWorksRW** [comment]
Just a note that while I don't mind having other files included in an attached zip file, they typically are not needed to fix an import problem. So if it's easier for you, please feel free to just include the .fbp file.

**Comment by KeyWorksRW** [comment]
Oops, I take that back -- having the generated files was extremely helpful in this case. The internal build of wxUiEditor lets me compare current code generation with what is already on disk, so I could look at the code generation you got and what I got and compare the differences. The most significant difference is that in your case, tool1 is set to class access of "none" whereas in the current build it's set to "protected:". wxFormBuilder does list that variable as "protected:" and the current build of wxUE correctly sets that as well during the import. In the meantime, I think if you change the permission to "protected:" you will be able to continue. I realize that's going to be a pain if there are multiple tools -- sorry about that. The other bugs have been fixed as well, but alas that still requires a current build.

I'm leaving this issue open because while all three listed problems are now working correctly, there's a fourth problem that this uncovers, which _does_ need to be fixed. Changing the permission of the tool to "none" should result in "auto* tool1 = " but instead it ignores the return and then tries to bind to the non-existent variable.

**Comment by KeyWorksRW** [comment]
Adding some warnings from the import:

bitmapsize(32,32) property in wxAuiToolBar class not supported
font(,90,400,-1,70,0) property in Panel class not supported
tab_ctrl_height(-1) property in wxAuiNotebook class not supported

bitmapsize should not be used if wxBitmapBundle is going to be used, but the other two need investigation as to why they aren't converting.

**Comment by KeyWorksRW** [comment]
The issue with the wxAuiToolBar tool has been fixed. Both bitmapsize and font are now processed. If memory serves, tab_ctrl_height doesn't actually work in wxAuiNotebook which is why we don't support it. I have created a separate issue #936 specific to tab height so that this issue can be closed as completed.
