### ISSUE TITLE
Enhance abilities of Image class

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#897]
### Description:

wxPython also supports embedded images, however if the images are used in more than one form, they will be duplicated unless they are added to the Images class. That makes the functionality of the Images class more valuable. However, currently it's a bit awkward to use -- namely because if you add an image to a control, you have to know that you have to add the same image to the Images class to have it created there instead of in the current form.

Possible improvements:

- Add property to automatically add images to this class whenever they are created in any control belonging to a form. This could also be form-specific instead.
- Add function to sort the images
- Add property to maintain list sorted
- Add ability to create a folder with a specific type, and and move all images of that type into that folder.

**Comment by Randalphwa** [comment]
I already tried having an auto feature that would automatically add the bitmaps, but it turned out very problematic. Undo was a significant problem, and enabling/disabling the property also created problems. It _can_ be done but will take a fair amount of time to implement fully and test. It's not worth holding up the 1.3 release for.

**Comment by KeyWorksRW** [comment]
Incoming PR will have a new `auto_add` property to automatically add images to the Image list whenever they are created in any control.

Images are always added in sorted order.

I'm dubious folders will ever work given the `auto_add` functionality.
