### ISSUE TITLE
Bug: Missing construction code for wxAuiToolbar disabled tool

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#944]
### Description:

Support for a disabled tool was added for wxToolbar, but I forgot to also add code generation for it to wxAuiToolbar. The use of the property does change the constructor to give us a temporary tool name to use, but doesn't generate the `Enable(false)` code.

**Comment by Randalphwa** [comment]
**wxAuiToolbar** doesn't have a `Enable(bool)` function the way **wxToolbar** does. Instead it has states for pressed, disabled, hidden and checked which are set via `SetState()`. Using these requires `#include <wx/aui/framemanager.h>` in order to get the state constants. That means that instead of using a single checkbox for disabled, a state property should be set with check boxes for the multiple states that can be combined.

I'm moving this into the 1.x release -- I don't want to hold up the 1.1 release to implement this.
