### ISSUE TITLE
Add property to disable wxStdDialogButtonSizer wxButton member generation

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#998]
### Description:

Currently, code generation for wxStdDialogButtonSizer generates wxButton* member variables for each button used. While that's fine if you need those variables, it results in warnings from clang-cl and clang-tidy about unused members. Usually, you don't actually need these -- calling functions like `GetAffirmativeButton()` allows you to access most buttons without needing member variables.

At the very least, we should add a property that let's the user disable generation of button members -- with the help text suggesting alternatives like `GetAffirmativeButton()`.

**Comment by Randalphwa** [comment]
This is actually a bug in it's current implementation. Currently, member variables are _only_ generated if `wxStdDialogButtonSizer` has class access set to something other than `none` (the default is none). However, while enabling class access does generate variables in the header file, it doesn't always assign them. The only time they get assigned is if the user requested a button that requires calling AddButton(new new wxButton). That only happens if the form is _not_ a dialog, either Save or ContextHelp buttons are requested.

It _is_ valid to create the class member variables if AddButton is called -- that should not generate a compiler warning since the variables are initialized in the source code, and there are marked as being used. While the dev might or might not need them, I don't think this case justifies a property to supress generation -- particularly since most of the time the variables won't be created even if the dev requests them.
